### ISSUE TITLE
inv_sig_helper currently failing causing "The media could not be loaded..."

### ISSUE THREAD

**Issue by Bobettemcnugget** [iv-org/inv_sig_helper#32]
Hello,

We've had a brief chat about this on Matrix however, here's a quick recap of the problem:

Currently all videos on my instance are showing the "The media could not be loaded..." error while using Dash.

Example video ID used while testing: StrqBbYFViI

This is the errors thrown by the dev tools:

`Uncaught (in promise) DOMException: The media resource indicated by the src attribute or assigned media provider object was not suitable.`

The invidious instance it self shows all 200s:

```
2024-11-14 15:27:59 UTC [info] 200 GET /watch?v=StrqBbYFViI 1251.34ms

2024-11-14 15:27:59 UTC [info] 200 GET /api/manifest/dash/id/StrqBbYFViI?local=true&unique_res=1 1.13ms

2024-11-14 15:27:59 UTC [info] 200 GET /api/v1/storyboards/StrqBbYFViI?height=90 1.7ms
```

inv_sig_helper throws the following:
```

[2024-11-14T15:27:58Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/0ccfa671/player_ias.vflset/en_US/base.js

[2024-11-14T15:27:59Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)

[2024-11-14T15:27:59Z INFO  inv_sig_helper_rust::player] sig code: var RCa;var TL={Se:function(a){a.reverse()},

    db:function(a,b){a.splice(0,b)},

    KQ:function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}};RCa=function(a){a=a.split("");TL.Se(a,12);TL.KQ(a,30);TL.Se(a,17);TL.db(a,1);return a.join("")}
[2024-11-14T15:27:59Z INFO  inv_sig_helper_rust::player] sig code: var RCa;var TL={Se:function(a){a.reverse()},

    db:function(a,b){a.splice(0,b)},

    KQ:function(a,b){var c=a[0];a[0]=a[b%a.length];a[b%a.length]=c}};RCa=function(a){a=a.split("");TL.Se(a,12);TL.KQ(a,30);TL.Se(a,17);TL.db(a,1);return a.join("")}
```

**Comment by unixfox** [comment]
this could actually be a non-issue this "did not work": https://github.com/iv-org/inv_sig_helper/issues/28

**Comment by Bubba8291** [comment]
I am having this issue now too. inv_sig_helper fails to start.
```
Dec 10 13:17:24 YT systemd[1]: Started inv_sig_helper (decrypt YouTube signatures and manage player information).
Dec 10 13:17:24 YT inv_sig_helper_rust[696]: [2024-12-10T21:17:24Z INFO  inv_sig_helper_rust] Fetching player
Dec 10 13:17:26 YT inv_sig_helper_rust[696]: [2024-12-10T21:17:26Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/3bb1f723/player_ias.vflset/en_US/base.js
Dec 10 13:17:29 YT inv_sig_helper_rust[696]: [2024-12-10T21:17:29Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
Dec 10 13:17:29 YT inv_sig_helper_rust[696]: thread 'main' panicked at src/player.rs:150:10:
Dec 10 13:17:29 YT inv_sig_helper_rust[696]: called `Option::unwrap()` on a `None` value
Dec 10 13:17:29 YT inv_sig_helper_rust[696]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Dec 10 13:17:29 YT systemd[1]: inv_sig_helper.service: Main process exited, code=killed, status=6/ABRT
Dec 10 13:17:29 YT systemd[1]: inv_sig_helper.service: Failed with result 'signal'.
Dec 10 13:17:31 YT systemd[1]: inv_sig_helper.service: Scheduled restart job, restart counter is at 24.
Dec 10 13:17:31 YT systemd[1]: Stopped inv_sig_helper (decrypt YouTube signatures and manage player information).
```

**Comment by Maloschnikow** [comment]
I have a similar issue, the docker container is in a restart loop and the log looks like this:
```
[2024-12-16T17:06:06Z INFO  inv_sig_helper_rust] Fetching player
[2024-12-16T17:06:06Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/2f1832d2/player_ias.vflset/en_US/base.js
[2024-12-16T17:06:06Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
thread 'main' panicked at src/player.rs:185:10:
called `Option::unwrap()` on a `None` value
```

**Comment by unixfox** [comment]
@Maloschnikow please create a separate issue. your issue is a new one
