### ISSUE TITLE
nsig function ending did not work

### ISSUE THREAD

**Issue by rockerBOO** [iv-org/inv_sig_helper#41]
Fixed in #43. Update your containers or make a new build. 

---

Running into the nsig function error again just now. Similar to #36 . Probably they changed how it worked again. 

```
inv_sig_helper-1  | [2024-12-16T17:42:51Z INFO  inv_sig_helper_rust] Fetching player
inv_sig_helper-1  | [2024-12-16T17:42:52Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/2f1832d2/player_ias.vflset/en_US/base.js
inv_sig_helper-1  | [2024-12-16T17:42:52Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
inv_sig_helper-1  | thread 'main' panicked at src/player.rs:185:10:
inv_sig_helper-1  | called `Option::unwrap()` on a `None` value
inv_sig_helper-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Note that this will take some time to make an update so only comment if you have new information or possible fixes. Subscribe on the side bar to get notification updates without making comments.

**Comment by gabe4278** [comment]
Probably because of YouTube updates.. and it broke, that's why there are problems?

**Comment by Drikanis** [comment]
Here's the full trace from my instance having the same issue in case it's needed:
```
[2024-12-16T17:48:45Z INFO  inv_sig_helper_rust] Fetching player
[2024-12-16T17:48:46Z INFO  inv_sig_helper_rust::player] Fetching player JS URL: https://www.youtube.com/s/player/2f1832d2/player_ias.vflset/en_US/base.js
[2024-12-16T17:48:46Z WARN  inv_sig_helper_rust::player] nsig function ending did not work: =\s*function(\([\w]+\)\{\s*var\s+[\w\s]+=[\w\.\s]+?\.call\s*\([\w\s$]+?,[\(\)\",\s]+\)[\S\s]*?\}\s*return [\w\.\s$]+?\.call\s*\([\w\s$]+?\s*,[\(\)\",\s]+\)\s*\}\s*;)
thread 'main' panicked at src/player.rs:185:10:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x7f2ad0c6b161 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h706c9783aace6373
   1:     0x7f2ad0ac765b - core::fmt::write::h7221bf2763310748
   2:     0x7f2ad0c44d52 - std::io::Write::write_fmt::h5f543a3ea7d45c3d
   3:     0x7f2ad0c702d9 - std::sys_common::backtrace::print::hf2079bcf21b5d607
   4:     0x7f2ad0c6fac6 - std::panicking::default_hook::{{closure}}::hd6a41ed4ba4d9cdd
   5:     0x7f2ad0c70ed1 - std::panicking::rust_panic_with_hook::he62aa99a29ab1fe6
   6:     0x7f2ad0c7060a - std::panicking::begin_panic_handler::{{closure}}::h4295830cbed5c147
   7:     0x7f2ad0c70599 - std::sys_common::backtrace::__rust_end_short_backtrace::h29724adceafc0e2c
   8:     0x7f2ad0c70586 - rust_begin_unwind
   9:     0x7f2ad0a3f432 - core::panicking::panic_fmt::h5822797b7c57c9a6
  10:     0x7f2ad0a3f5cb - core::panicking::panic::h576d2b304e82d017
  11:     0x7f2ad0a3f988 - core::option::unwrap_failed::hf12f69fdafb5c188
  12:     0x7f2ad0a7eb59 - inv_sig_helper_rust::player::fetch_update::{{closure}}::hbc289594c89fa552
  13:     0x7f2ad0a97a78 - inv_sig_helper_rust::main::{{closure}}::h92460df08abff2f1
  14:     0x7f2ad0a8ec2a - inv_sig_helper_rust::main::h4c6ed7911b8effb7
  15:     0x7f2ad0a554f3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h65fca62ed9181c86
  16:     0x7f2ad0a9afb4 - main
```

**Comment by lifo9** [comment]
Fix https://0x0.st/XFGc.patch

**Comment by gabe4278** [comment]
Worked, thx!

**Comment by rockerBOO** [comment]
Tested and working. Temporary container at https://hub.docker.com/r/rockerboo/inv_sig_helper until PR is merged
